### ISSUE TITLE
Crash - Attempt to invoke interface method 'boolean android.view.ViewParent.showContextMenuForChild(android.view.View, float, float)' on a null object reference

### ISSUE THREAD

**Issue by pankaj610** [mpiannucci/react-native-context-menu-view#134]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ViewParent.showContextMenuForChild(android.view.View, float, float)' on a null object reference
       at android.view.View.showContextMenu(View.java:7739)
       at com.mpiannucci.reactnativecontextmenu.ContextMenuView$1.onSingleTapConfirmed(ContextMenuView.java:56)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:333)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
       
       I am getting the above error in production for some users, currently, i have added the error handling as shown below. Let me know if there is another solution and release the fix in upcoming version
       
```
try {
                            if (getParent() != null) {
                                showContextMenu(e.getX(), e.getY());
                            } else {
                                Log.e("ContextMenuView", "Parent view is null, cannot show context menu.");
                            }
                        } catch (NullPointerException ex) {
                            Log.e("ContextMenuView", "Failed to show context menu due to null reference", ex);
                        }
```

**Comment by Mahmoud85** [comment]
@iampankajver iampankajver , was you able to get a solution for this?

**Comment by dhairyasenjaliya** [comment]
hi we are seeing this as well any solution or fixes
